namespace NetlinkCore.Interop.Generic;

internal enum ethtool_stringset
{
    ETH_SS_TEST = 0,
    ETH_SS_STATS,
    ETH_SS_PRIV_FLAGS,
    ETH_SS_NTUPLE_FILTERS,
    ETH_SS_FEATURES,
    ETH_SS_RSS_HASH_FUNCS,
    ETH_SS_TUNABLES,
    ETH_SS_PHY_STATS,
    ETH_SS_PHY_TUNABLES,
    ETH_SS_LINK_MODES,
    ETH_SS_MSG_CLASSES,
    ETH_SS_WOL_MODES,
    ETH_SS_SOF_TIMESTAMPING,
    ETH_SS_TS_TX_TYPES,
    ETH_SS_TS_RX_FILTERS,
    ETH_SS_UDP_TUNNEL_TYPES,
    ETH_SS_STATS_STD,
    ETH_SS_STATS_ETH_PHY,
    ETH_SS_STATS_ETH_MAC,
    ETH_SS_STATS_ETH_CTRL,
    ETH_SS_STATS_RMON
}